# Generated by Django 3.2.6 on 2021-11-25 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='brake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='cumulative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='cumulativeMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='deliveryTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
