# Generated by Django 3.2.6 on 2021-11-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_auto_20211125_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calcelations',
            field=models.IntegerField(default=0),
        ),
    ]
