# Generated by Django 3.2.6 on 2021-11-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_user_calcelations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='calcelations',
            new_name='cancelations',
        ),
    ]
