# Generated by Django 3.2.6 on 2021-12-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_rename_calcelations_user_cancelations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='C:\\Projects')),
                ('filepath', models.CharField(max_length=999)),
                ('content', models.CharField(max_length=999)),
            ],
        ),
    ]
