# Generated by Django 3.2.6 on 2021-12-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
