# Generated by Django 3.2.6 on 2021-12-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_remove_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='filepath',
        ),
    ]
