# Generated by Django 3.2.6 on 2021-12-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_remove_blog_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='filename',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
