# Generated by Django 3.2.6 on 2021-12-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0008_auto_20211205_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='filename',
        ),
    ]
