# Generated by Django 3.2.6 on 2021-12-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0009_remove_blog_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='filename',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='filepath',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
