# Generated by Django 3.2.6 on 2021-12-05 11:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0011_alter_blog_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/images'), upload_to=''),
        ),
    ]
