# Generated by Django 3.2.6 on 2021-12-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0012_alter_blog_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
