# Generated by Django 3.2.6 on 2021-12-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0013_alter_blog_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('filepath', models.CharField(max_length=999, null=True)),
                ('filename', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
