# Generated by Django 3.2.6 on 2021-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0014_auto_20211205_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('content1', models.CharField(max_length=999, null=True)),
                ('content2', models.CharField(max_length=999, null=True)),
                ('content3', models.CharField(max_length=999, null=True)),
                ('content4', models.CharField(max_length=999, null=True)),
                ('content5', models.CharField(max_length=999, null=True)),
                ('url1', models.CharField(max_length=256, null=True)),
                ('url2', models.CharField(max_length=256, null=True)),
                ('url3', models.CharField(max_length=256, null=True)),
                ('url4', models.CharField(max_length=256, null=True)),
                ('url5', models.CharField(max_length=256, null=True)),
                ('contentmap', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
