# Generated by Django 3.2.6 on 2021-12-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0016_image_blogid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=999, null=True)),
                ('blogid', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contentmap',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url5',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogimage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bakery.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogcontent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bakery.content'),
        ),
    ]
