# Generated by Django 3.2.6 on 2021-12-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0017_auto_20211211_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogcontent',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blogimage',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogid',
            field=models.IntegerField(default=0),
        ),
    ]
