# Generated by Django 3.2.6 on 2021-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0018_auto_20211212_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isTitleImage',
            field=models.CharField(default='no', max_length=999, null=True),
        ),
    ]
