# Generated by Django 3.2.6 on 2021-12-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0019_content_istitleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='isTitleImage',
            field=models.BooleanField(default=False),
        ),
    ]
