# Generated by Django 3.2.6 on 2021-12-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0021_alter_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='breadType',
            field=models.CharField(choices=[('White Bread', 'White Bread'), ('Country Bread', 'Country Bread'), ('Oat Porridge Bread', 'Oat Porridge Bread'), ('Semolina Bread', 'Semolina Bread'), ('100% Rye Bread', '100% Rye Bread'), ('Seeded', 'Seeded'), ('Baguette', 'Baguette'), ('Sweet Brioche', 'Sweet Brioche')], max_length=64),
        ),
    ]
